source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bower-rails'
gem 'angular-rails-templates'
gem 'haml-rails'
gem 'devise', '~> 3.4'
gem 'cancancan', '~> 1.10'
gem 'angular_rails_csrf'
gem 'omniauth-facebook'
gem 'acts_as_list'
gem 'carrierwave'
gem 'angularjs-file-upload-rails', '~> 1.1.6'
gem 'json_spec'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.2'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  gem 'faker'
  gem 'shoulda-matchers'
end

gem 'rails_12factor', group: :production