# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef8204e5b6a6c7d2a57f6706877527f167007e86f7ac68b474ceeb7505292ccc98ccbfa1e169b5a5f0ed86b3d1fe9568506f26035adfdaf6721148a6cfbe034

test:
  secret_key_base: db9895a646bd1af3cb431a5a969384136c539f23b2e4428671c0b055719fc8bce1c906e7378d37cf7a3403cfc53a8bf14d58f8ae541d1579545543b6e99163a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fdsfds
  secret_token: fdsfds
